### ISSUE TITLE
Could not resolve route "./feature/feature.module#FeatureModule"

### ISSUE THREAD

**Issue by anabulsi** [daniele-zurico/webpack-aot#2]
Was following the tutorial at http://www.dzurico.com/angular-aot-webpack-lazy-loading/

I cloned the repo and did the npm install. But whenever i try to run it using npm run build i get the error:

```
> test@ build C:\Users\Shawerma\Desktop\webpack-aot
> webpack --config webpack.config.js

Error: Could not resolve route "./feature/feature.module#FeatureModule" from file "app\lazy.module".
    at C:\Users\Shawerma\Desktop\webpack-aot\node_modules\@ngtools\webpack\src\plugin.js:277:23
    at Array.map (native)
    at AotPlugin._processNgModule (C:\Users\Shawerma\Desktop\webpack-aot\node_modules\@ngtools\webpack\src\plugin.js:273:14)
    at _loop_1 (C:\Users\Shawerma\Desktop\webpack-aot\node_modules\@ngtools\webpack\src\plugin.js:306:35)
    at AotPlugin._processNgModule (C:\Users\Shawerma\Desktop\webpack-aot\node_modules\@ngtools\webpack\src\plugin.js:325:13)
    at C:\Users\Shawerma\Desktop\webpack-aot\node_modules\@ngtools\webpack\src\plugin.js:242:39
```

I'm I doing anything wrong?

**Comment by daniele-zurico** [comment]
try now! just updated to webpack 2.2

**Comment by anabulsi** [comment]
It's working now. Thanks
